### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by imjuzcy** [dreautall/bluecoins-to-fireflyiii#10]
There were some bugs regarding foreign currency transactions and transaction linking for split transactions, which I have fixed in [my fork](https://github.com/imjuzcy/bluecoins-to-fireflyiii/tree/fix-bugs) in the branch `fix-bugs`. I have also added the option to use description as the opposing account name. @dreautall should I open a pull request?

**Comment by dreautall** [comment]
Hi, yes please open a PR - I guess it's the easiest way.

Thank you for your work!
